### ISSUE TITLE
suggest $LOG_COUNT should be an optional parameter for user to input

### ISSUE THREAD

**Issue by timmyz** [cryptape/cita-op-helper#4]
https://github.com/cryptape/cita-op-helper/blob/79df066c156504eb657c62d45d8d708952f86bf7/cita-op-helper#L5

sometimes `50` lines logs are not enough for analysis.

**Comment by rainchen** [comment]
@timmyz what is your suggestion?

**Comment by timmyz** [comment]
> @timmyz what is your suggestion?

maybe like this:
```
./cita-op-helper /data/cita_secp256k1_sha3 -n 100
```
here `100` means last 100 lines of each log file.

**Comment by rainchen** [comment]
this feature accomplished in PR #5

**Comment by rainchen** [comment]
close this for now, since  #5
but looking for a better parameter style like `-n 100`
